In [1]:
import pandas as pd
from openpyxl import load_workbook
import os
import numpy as np

In [2]:
data_path = '..\\datasets'
files = os.listdir(data_path)
files.remove('URL descripcion reto.txt')
files.remove('leeme.txt')
dfs = {}

def open_file(file_name):
    file_path = os.path.join(data_path, file_name)

    # Cargar todas las hojas con pandas.read_excel(sheet_name=None)
    all_sheets = pd.read_excel(file_path, sheet_name=None)

    # Guardar cada hoja en dfs con un nombre único combinando el archivo y la hoja
    for sheet_name, data in all_sheets.items():
        # Crear un nombre único para el DataFrame usando el nombre del archivo y la hoja
        df_name = f"{file_name.replace('.xlsx', '')}_{sheet_name}"
        dfs[df_name] = data


# Abrir todos los archivos y leer todas las hojas
for file in files:
    if file.endswith('.xlsx'):  # Asegurarse de que solo se procesen archivos Excel
        open_file(file)

In [3]:
print(dfs.keys())

dict_keys(['Biorreactor 13169_WData', 'Biorreactor 13169_Datos', 'Biorreactor 13170_WData', 'Biorreactor 13170_Datos', 'Biorreactor 13171_WData', 'Biorreactor 13171_Datos', 'Biorreactor 13172_WData', 'Biorreactor 13172_Datos', 'Biorreactor 14614_Datos', 'Biorreactor 14615_WData', 'Biorreactor 14615_Datos', 'Biorreactor 14616_WData', 'Biorreactor 14616_Datos', 'Biorreactor 14617_WData', 'Biorreactor 14617_Datos', 'Biorreactor 14618_WData', 'Biorreactor 14618_Datos', 'Centrífuga 12912_WData', 'Centrífuga 12912_Datos', 'Centrífuga 14246_WData', 'Centrífuga 14246_Datos', 'Centrífuga 17825_WData', 'Centrífuga 17825_Datos', 'Cinéticos IPC_Inóculos', 'Cinéticos IPC_Cultivos finales', 'Cinéticos IPC_Centrifugación', 'Fases producción v02_Preinóculo', 'Fases producción v02_Inóculo', 'Fases producción v02_Cultivo final', 'Fases producción v03 Test_Cultivo final', 'Fases producción v03_Preinóculo', 'Fases producción v03_Inóculo', 'Fases producción v03_Cultivo final', 'Fases producción_test v02_Cultivo final', 'Horas inicio fin centrífugas_Hoja1', 'Movimientos componentes_Full1', 'OF 123456 v02_Sheet1', 'OF 123456 v03_Sheet1', 'Temperaturas y humedades_WData', 'Temperaturas y humedades_Datos'])

In [6]:
# Acceder a los DataFrames

df_preinoculo = dfs['Fases producción v03_Preinóculo']
df_preinoculo.columns = df_preinoculo.iloc[0]
df_preinoculo = df_preinoculo.drop(0)
df_inoculo = dfs['Fases producción v03_Inóculo']
df_cultivo_final = dfs['Fases producción v03 Test_Cultivo final']

# Unir los tres DataFrames por la columna 'LOTE'
merged_df = df_preinoculo.merge(df_inoculo, on='LOTE', suffixes=('_preinoculo', '_inoculo'), how='right')
merged_df = merged_df.merge(df_cultivo_final, on='LOTE', suffixes=('', '_cultivo_final'), how='right')
merged_df['ID Centrífuga'] = merged_df['ID Centrífuga'].astype(int)
merged_df['ID Bioreactor'] = merged_df['ID Bioreactor'].astype(int)
mode_value = merged_df['ID bioreactor'].mode().iloc[0]  # Get the first mode
merged_df['ID bioreactor'].fillna(mode_value, inplace=True)
merged_df['ID bioreactor'].replace([float('inf'), -float('inf')], mode_value, inplace=True)
merged_df['ID bioreactor'] = merged_df['ID bioreactor'].astype(int)

C:\Users\jaime\AppData\Local\Temp\ipykernel_24764\228738362.py:11: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  merged_df = merged_df.merge(df_cultivo_final, on='LOTE', suffixes=('', '_cultivo_final'), how='right')

In [7]:
merged_df

,LOTE,Fecha/hora inicio_preinoculo,Fecha/hora fin_preinoculo,línea 1,línea 2,línea 3,línea 1,línea 2,línea 3,línea 1,...,Fecha/hora fin,Volumen de inóculo utilizado,Turbidez inicio cultivo_cultivo_final,Turbidez fin cultivo,Viabilidad final cultivo_cultivo_final,ID Centrífuga,Centrifugación 1 turbidez,Centrifugación 2 turbidez,Producto 1,Producto 2
0,24054.0,2024-04-14 00:30:00,2024-04-15 07:17:00,5.504,5.376,5.376,27.12,25.68,29.52,1,...,2024-04-18 07:28:00,81.60,15.44,85.60,184800000,14246,27.84,23.96,NaN,NaN
1,24055.0,2024-04-11 00:30:00,2024-04-12 07:14:00,5.368,5.416,5.464,26.16,25.52,25.04,1,...,2024-04-15 08:30:00,NaN,14.32,73.68,175200000,12912,30.96,23.16,NaN,NaN
2,24056.0,2024-04-11 00:30:00,2024-04-12 07:14:00,5.368,5.416,5.464,26.16,25.52,25.04,1,...,2024-04-15 08:15:00,NaN,14.56,82.40,168000000,14246,29.52,28.88,NaN,NaN
3,24057.0,2024-04-14 00:30:00,2024-04-15 07:17:00,5.504,5.376,5.376,27.12,25.68,29.52,1,...,2024-04-18 07:41:00,82.40,17.76,78.96,180800000,12912,31.04,25.32,NaN,NaN
4,24058.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-04-17 08:14:00,87.20,18.00,82.40,144800000,12912,26.08,20.36,NaN,NaN
5,24059.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-04-17 08:22:00,87.20,18.08,78.40,166400000,14246,26.88,23.64,NaN,NaN
6,24060.0,2024-04-18 00:30:00,2024-04-19 07:46:00,5.384,5.344,5.448,25.44,26,24.72,1,...,2024-04-22 09:12:00,82.40,25.92,76.32,161600000,14246,32.56,17.92,NaN,NaN
7,24061.0,2024-04-18 00:30:00,2024-04-19 07:46:00,5.384,5.344,5.448,25.44,26,24.72,1,...,2024-04-22 09:12:00,81.60,28.56,68.96,148800000,12912,27.76,14.72,NaN,NaN
8,24062.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-04-19 08:05:00,87.20,18.88,80.00,164800000,12912,27.52,24.64,NaN,NaN
9,24063.0,2024-04-21 00:30:00,2024-04-22 07:19:00,5.36,5.376,NaN,25.84,27.84,NaN,1,...,2024-04-25 11:14:00,NaN,15.52,68.72,180800000,12912,25.92,18.28,NaN,NaN
10,24064.0,2024-04-21 00:30:00,2024-04-22 07:19:00,5.36,5.376,NaN,25.84,27.84,NaN,1,...,2024-04-25 11:10:00,NaN,18.56,63.76,174400000,14246,29.36,12.48,NaN,NaN
11,24065.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-04-24 09:25:00,80.00,18.48,77.60,209600000,14246,29.28,25.16,NaN,NaN
12,24066.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-04-24 09:22:00,80.00,19.60,77.44,118400000,12912,27.44,21.44,NaN,NaN
13,24067.0,2024-04-25 00:30:00,2024-04-26 07:17:00,5.568,5.56,5.52,20.96,22.48,22.4,0,...,2024-04-29 08:57:00,82.96,16.96,76.88,177600000,17825,32.16,18.20,NaN,NaN
14,24068.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-04-26 07:11:00,80.00,21.20,80.00,173600000,14246,30.00,22.24,NaN,NaN
15,24069.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-04-26 11:13:00,80.00,19.92,64.40,160000000,12912,31.76,25.36,NaN,NaN
16,24070.0,2024-04-25 00:30:00,2024-04-26 07:17:00,5.568,5.56,5.52,20.96,22.48,22.4,0,...,2024-04-29 09:05:00,82.96,16.40,81.60,168000000,14246,30.00,22.52,NaN,NaN
17,24071.0,2024-04-28 00:30:00,2024-04-29 07:45:00,6.28,5.488,NaN,27.36,24.88,NaN,0,...,2024-05-02 07:36:00,80.40,16.16,84.80,195200000,12912,30.48,22.36,NaN,NaN
18,24072.0,2024-05-12 00:30:00,2024-05-13 08:16:00,5.424,5.424,NaN,25.36,30.96,NaN,0,...,2024-05-16 07:19:00,83.20,18.48,78.40,191200000,14246,31.92,19.28,NaN,NaN
19,24073.0,2024-05-12 00:30:00,2024-05-13 07:54:00,5.44,5.384,5.456,25.12,26.96,27.84,0,...,2024-05-16 08:08:00,83.60,18.72,71.36,197600000,17825,34.40,22.28,NaN,NaN
20,24074.0,2024-05-16 00:30:00,2024-05-17 07:15:00,5.408,5.408,5.384,27.36,28.08,24.32,1,...,2024-05-20 08:21:00,82.40,15.76,76.16,163200000,14246,26.56,19.44,NaN,NaN
21,24076.0,2024-05-16 00:30:00,2024-05-17 07:15:00,5.408,5.408,5.384,27.36,28.08,24.32,1,...,2024-05-20 08:20:00,82.00,16.24,81.60,204800000,12912,29.60,24.56,NaN,NaN
22,24077.0,2024-05-19 00:30:00,2024-05-20 07:14:00,5.4,5.384,5.4,30.96,27.76,26.24,1,...,2024-05-23 07:55:00,82.00,18.00,85.60,172800000,17825,33.92,26.20,NaN,NaN
23,24078.0,2024-05-19 00:30:00,2024-05-20 07:14:00,5.4,5.384,5.4,30.96,27.76,26.24,1,...,2024-05-23 07:55:00,81.20,17.68,75.12,173600000,14246,29.36,20.88,NaN,NaN
24,24079.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-05-22 09:19:00,NaN,18.72,88.80,124000000,14246,28.72,24.16,NaN,NaN
25,24080.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-05-22 09:16:00,NaN,19.44,80.00,90400000,17825,29.44,21.24,NaN,NaN
26,24081.0,2024-05-26 00:30:00,2024-05-27 08:05:00,5.44,5.504,5.496,29.68,31.2,28.96,1,...,2024-05-30 07:06:00,80.40,18.88,79.84,166400000,14246,29.84,18.20,NaN,NaN
27,24082.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-05-24 10:02:00,NaN,18.48,85.60,169600000,14246,27.20,23.52,NaN,NaN
28,24083.0,2024-05-23 00:30:00,2024-05-24 07:26:00,5.384,5.4,5.4,25.84,30.24,29.68,1,...,2024-05-27 08:35:00,85.20,18.32,74.48,180000000,17825,30.24,17.20,NaN,NaN
29,24084.0,2024-05-23 00:30:00,2024-05-24 07:26:00,5.384,5.4,5.4,25.84,30.24,29.68,1,...,2024-05-27 09:19:00,81.60,17.92,74.96,163200000,14246,27.92,16.92,NaN,NaN
30,24085.0,2024-05-26 00:30:00,2024-05-27 08:05:00,5.44,5.504,5.496,29.68,31.2,28.96,1,...,2024-05-30 08:10:00,80.00,16.32,81.60,173600000,17825,30.80,23.80,NaN,NaN
31,24086.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-05-29 09:10:00,NaN,20.40,74.40,149600000,12912,27.60,18.84,NaN,NaN
32,24087.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-05-29 09:13:00,NaN,16.72,74.16,171200000,14246,25.20,18.64,NaN,NaN
33,24088.0,2024-05-30 00:30:00,2024-05-31 07:46:00,5.472,5.616,5.48,30.56,31.2,29.68,1,...,2024-06-03 08:53:00,83.20,18.32,64.80,158400000,12912,26.88,13.24,NaN,NaN
34,24089.0,2024-05-30 00:30:00,2024-05-31 07:46:00,5.472,5.616,5.48,30.56,31.2,29.68,1,...,2024-06-03 08:43:00,82.40,18.00,71.44,148000000,14246,27.68,15.00,NaN,NaN
35,24090.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-05-31 09:39:00,NaN,19.76,73.52,144800000,12912,26.08,19.56,NaN,NaN
36,24091.0,2024-06-02 00:30:00,2024-06-03 07:03:00,5.392,5.424,5.472,33.44,32.16,29.36,1,...,2024-06-06 07:50:00,82.40,14.00,85.60,195200000,12912,30.48,27.76,NaN,NaN
37,24092.0,2024-06-02 00:30:00,2024-06-03 07:03:00,5.392,5.424,5.472,33.44,32.16,29.36,1,...,2024-06-06 08:06:00,82.00,16.72,101.60,223200000,17825,38.80,39.04,NaN,NaN
38,24093.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-06-05 07:14:00,NaN,15.92,73.76,214400000,12912,23.76,22.12,NaN,NaN
39,24094.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-06-05 07:18:00,NaN,14.24,78.00,204800000,14246,22.32,19.72,NaN,NaN
40,24095.0,2024-06-09 00:30:00,2024-06-10 07:09:00,5.456,5.44,5.432,32.08,31.28,28.72,1,...,2024-06-13 07:03:00,82.40,20.80,82.40,246400000,17825,42.32,35.28,NaN,NaN
41,24096.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-06-07 09:03:00,NaN,33.44,101.60,230400000,14246,33.92,31.40,NaN,NaN
42,24097.0,2024-06-09 00:30:00,2024-06-10 07:09:00,5.456,5.44,5.432,32.08,31.28,28.72,1,...,2024-06-13 07:03:00,82.40,22.24,87.20,240800000,12912,37.12,18.84,NaN,NaN
43,24098.0,2024-06-13 00:30:00,2024-06-14 08:00:00,5.672,5.608,5.608,23.04,22.56,20.96,1,...,2024-06-17 10:45:00,87.12,19.60,62.40,138400000,12912,32.00,14.48,NaN,NaN
44,24099.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-06-19 09:34:00,80.00,19.52,78.48,165600000,12912,29.60,18.60,NaN,NaN
45,24100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-06-21 07:51:00,80.00,20.80,84.00,216800000,12912,32.80,24.64,NaN,NaN
46,24101.0,2024-06-27 00:30:00,2024-06-28 07:16:00,5.424,5.432,5.416,32.08,32.48,30.64,1,...,2024-07-01 07:46:00,81.60,19.28,92.00,157600000,12912,31.84,23.48,NaN,NaN
47,24103.0,2024-06-27 00:30:00,2024-06-28 07:16:00,5.424,5.432,5.416,32.08,32.48,30.64,1,...,2024-07-01 07:49:00,82.40,19.04,84.80,172800000,14246,29.44,19.76,NaN,NaN
48,24104.0,2024-06-30 00:30:00,2024-07-01 07:01:00,5.408,5.424,5.392,27.44,26.48,26.64,1,...,2024-07-04 08:43:00,83.60,20.16,82.40,171200000,14246,30.80,20.56,NaN,NaN
49,24105.0,2024-06-30 00:30:00,2024-07-01 07:01:00,5.408,5.424,5.392,27.44,26.48,26.64,1,...,2024-07-04 08:39:00,83.60,19.28,84.80,173600000,17825,31.84,19.16,NaN,NaN
50,24106.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-07-03 08:19:00,80.00,23.60,84.00,163200000,12912,32.40,26.40,NaN,NaN
51,24107.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-07-03 08:37:00,80.00,21.76,87.20,151200000,14246,28.32,23.28,NaN,NaN
52,24108.0,2024-07-04 00:30:00,2024-07-05 07:04:00,5.528,5.432,5.504,33.44,28.8,25.6,0,...,2024-07-08 08:29:00,84.40,20.16,81.60,159200000,14246,29.92,15.40,NaN,NaN
53,24109.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-07-05 08:23:00,80.00,23.84,94.40,196000000,12912,31.84,28.68,NaN,NaN
54,24110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-07-05 08:26:00,80.00,26.56,104.80,157600000,14246,34.40,27.80,NaN,NaN

In [8]:
def load_centrifuga_data(id_centrifuga):
    file_name = f'Centrífuga {id_centrifuga}_Datos'
    try:
        # Intentar cargar el DataFrame de centrífuga
        centrifuga_df = dfs[file_name]
        return centrifuga_df
    except KeyError:
        # Si el archivo no existe, retornar un DataFrame vacío o NaN
        return pd.DataFrame()  # o simplemente return np.nan si prefieres


def calculate_mean_for_lote(c, fecha_inicio, fecha_fin, id_centrifuga):
    centrifuga_df = load_centrifuga_data(id_centrifuga)
    
    if centrifuga_df.empty:
        return np.nan  # Si no hay datos, devolver NaN
    mask = (pd.to_datetime(centrifuga_df['DateTime']) >= pd.to_datetime(fecha_inicio)) & (pd.to_datetime(centrifuga_df['DateTime']) <= pd.to_datetime(fecha_fin))
    filtered_data = centrifuga_df[mask]
    return filtered_data[f'{id_centrifuga}_D01916047.PV'].mean()

merged_df['media_PV'] = merged_df.apply(
    lambda row: calculate_mean_for_lote(row['LOTE'], row['Fecha/hora inicio'], row['Fecha/hora fin'], row['ID Centrífuga']),
    axis=1
)

In [9]:

import pandas as pd
import numpy as np

# Function to load bioreactor data based on the given ID
def load_bioreactor_data(id_bioreactor):
    file_name = f'Biorreactor {id_bioreactor}_Datos'
    try:
        # Attempt to load the DataFrame of the bioreactor
        bioreactor_df = dfs[file_name]
        return bioreactor_df
    except KeyError:
        # If the file does not exist, return an empty DataFrame
        return pd.DataFrame()  # Alternatively, return np.nan if preferred

# Function to calculate the mean for the specified lot and bioreactor
def calculate_mean_for_lote2(lote, fecha_inicio, fecha_fin, id_bioreactor):
    bioreactor_df = load_bioreactor_data(id_bioreactor)
    
    if bioreactor_df.empty:
        return np.nan, np.nan, np.nan  # Return NaN for all means if there's no data

    # Filter the data based on the specified date range
    mask = (pd.to_datetime(bioreactor_df['DateTime']) >= pd.to_datetime(fecha_inicio)) & \
           (pd.to_datetime(bioreactor_df['DateTime']) <= pd.to_datetime(fecha_fin))
    filtered_data = bioreactor_df[mask]
    
    # Calculate means for the specified columns
    mean_temp = filtered_data[f'{id_bioreactor}_FERM0101.Temperatura_PV'].mean() if not filtered_data.empty else np.nan
    mean_ph = filtered_data[f'{id_bioreactor}_FERM0101.Single_Use_pH_PV'].mean() if not filtered_data.empty else np.nan
    mean_do = filtered_data[f'{id_bioreactor}_FERM0101.Single_Use_DO_PV'].mean() if not filtered_data.empty else np.nan
    
    return mean_temp, mean_ph, mean_do

# Apply the function to each row of merged_df and store the results in new columns
merged_df[['media_temp_bioreactor', 'media_ph_biorreactor', 'media_PO_biorreactor']] = merged_df.apply(
    lambda row: calculate_mean_for_lote2(row['LOTE'], row['Fecha/hora inicio_inoculo'], row['Fecha/hora fin_inoculo'], row['ID bioreactor']),
    axis=1,
    result_type='expand'  # This allows unpacking into multiple columns
)

In [10]:
merged_df = merged_df.fillna("NA")
output_file_path = '../dataset_test.csv'  # Cambia esto a la ruta donde quieras guardar el archivo
merged_df.to_csv(output_file_path, index=False)

In [11]:
merged_df

,LOTE,Fecha/hora inicio_preinoculo,Fecha/hora fin_preinoculo,línea 1,línea 2,línea 3,línea 1,línea 2,línea 3,línea 1,...,Viabilidad final cultivo_cultivo_final,ID Centrífuga,Centrifugación 1 turbidez,Centrifugación 2 turbidez,Producto 1,Producto 2,media_PV,media_temp_bioreactor,media_ph_biorreactor,media_PO_biorreactor
0,24054.0,2024-04-14 00:30:00,2024-04-15 07:17:00,5.504,5.376,5.376,27.12,25.68,29.52,1,...,184800000,14246,27.84,23.96,NA,NA,0.827060,29.523502,5.889634,23.939733
1,24055.0,2024-04-11 00:30:00,2024-04-12 07:14:00,5.368,5.416,5.464,26.16,25.52,25.04,1,...,175200000,12912,30.96,23.16,NA,NA,0.404667,29.478246,5.909516,24.440044
2,24056.0,2024-04-11 00:30:00,2024-04-12 07:14:00,5.368,5.416,5.464,26.16,25.52,25.04,1,...,168000000,14246,29.52,28.88,NA,NA,0.400940,29.478246,5.909516,24.440044
3,24057.0,2024-04-14 00:30:00,2024-04-15 07:17:00,5.504,5.376,5.376,27.12,25.68,29.52,1,...,180800000,12912,31.04,25.32,NA,NA,0.503527,29.523502,5.889634,23.939733
4,24058.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,144800000,12912,26.08,20.36,NA,NA,0.101789,NA,NA,NA
5,24059.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,166400000,14246,26.88,23.64,NA,NA,0.355546,NA,NA,NA
6,24060.0,2024-04-18 00:30:00,2024-04-19 07:46:00,5.384,5.344,5.448,25.44,26,24.72,1,...,161600000,14246,32.56,17.92,NA,NA,0.416348,29.480435,5.881805,24.754048
7,24061.0,2024-04-18 00:30:00,2024-04-19 07:46:00,5.384,5.344,5.448,25.44,26,24.72,1,...,148800000,12912,27.76,14.72,NA,NA,0.406509,29.480435,5.881805,24.754048
8,24062.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,164800000,12912,27.52,24.64,NA,NA,0.974513,NA,NA,NA
9,24063.0,2024-04-21 00:30:00,2024-04-22 07:19:00,5.36,5.376,NA,25.84,27.84,NA,1,...,180800000,12912,25.92,18.28,NA,NA,0.531368,29.46004,5.866393,24.954162
10,24064.0,2024-04-21 00:30:00,2024-04-22 07:19:00,5.36,5.376,NA,25.84,27.84,NA,1,...,174400000,14246,29.36,12.48,NA,NA,0.539325,29.46004,5.866393,24.954162
11,24065.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,209600000,14246,29.28,25.16,NA,NA,0.161369,NA,NA,NA
12,24066.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,118400000,12912,27.44,21.44,NA,NA,0.122490,NA,NA,NA
13,24067.0,2024-04-25 00:30:00,2024-04-26 07:17:00,5.568,5.56,5.52,20.96,22.48,22.4,0,...,177600000,17825,32.16,18.20,NA,NA,0.465727,29.48612,6.146519,26.269442
14,24068.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,173600000,14246,30.00,22.24,NA,NA,0.998985,NA,NA,NA
15,24069.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,160000000,12912,31.76,25.36,NA,NA,0.907737,NA,NA,NA
16,24070.0,2024-04-25 00:30:00,2024-04-26 07:17:00,5.568,5.56,5.52,20.96,22.48,22.4,0,...,168000000,14246,30.00,22.52,NA,NA,0.412848,29.48612,6.146519,26.269442
17,24071.0,2024-04-28 00:30:00,2024-04-29 07:45:00,6.28,5.488,NA,27.36,24.88,NA,0,...,195200000,12912,30.48,22.36,NA,NA,0.406727,29.48249,6.372356,37.854963
18,24072.0,2024-05-12 00:30:00,2024-05-13 08:16:00,5.424,5.424,NA,25.36,30.96,NA,0,...,191200000,14246,31.92,19.28,NA,NA,0.428344,29.427946,5.88899,29.490308
19,24073.0,2024-05-12 00:30:00,2024-05-13 07:54:00,5.44,5.384,5.456,25.12,26.96,27.84,0,...,197600000,17825,34.40,22.28,NA,NA,0.466791,29.479909,5.919956,23.717667
20,24074.0,2024-05-16 00:30:00,2024-05-17 07:15:00,5.408,5.408,5.384,27.36,28.08,24.32,1,...,163200000,14246,26.56,19.44,NA,NA,0.409116,29.566466,5.888771,25.377197
21,24076.0,2024-05-16 00:30:00,2024-05-17 07:15:00,5.408,5.408,5.384,27.36,28.08,24.32,1,...,204800000,12912,29.60,24.56,NA,NA,0.408829,29.566466,5.888771,25.377197
22,24077.0,2024-05-19 00:30:00,2024-05-20 07:14:00,5.4,5.384,5.4,30.96,27.76,26.24,1,...,172800000,17825,33.92,26.20,NA,NA,0.748558,29.47042,5.95025,24.64777
23,24078.0,2024-05-19 00:30:00,2024-05-20 07:14:00,5.4,5.384,5.4,30.96,27.76,26.24,1,...,173600000,14246,29.36,20.88,NA,NA,0.588050,29.47042,5.95025,24.64777
24,24079.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,124000000,14246,28.72,24.16,NA,NA,0.117801,NA,NA,NA
25,24080.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,90400000,17825,29.44,21.24,NA,NA,0.149854,NA,NA,NA
26,24081.0,2024-05-26 00:30:00,2024-05-27 08:05:00,5.44,5.504,5.496,29.68,31.2,28.96,1,...,166400000,14246,29.84,18.20,NA,NA,0.584167,29.470456,-788.163643,24.901313
27,24082.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,169600000,14246,27.20,23.52,NA,NA,1.066912,NA,NA,NA
28,24083.0,2024-05-23 00:30:00,2024-05-24 07:26:00,5.384,5.4,5.4,25.84,30.24,29.68,1,...,180000000,17825,30.24,17.20,NA,NA,0.471373,29.468078,5.926895,23.654534
29,24084.0,2024-05-23 00:30:00,2024-05-24 07:26:00,5.384,5.4,5.4,25.84,30.24,29.68,1,...,163200000,14246,27.92,16.92,NA,NA,0.463456,29.468078,5.926895,23.654534
30,24085.0,2024-05-26 00:30:00,2024-05-27 08:05:00,5.44,5.504,5.496,29.68,31.2,28.96,1,...,173600000,17825,30.80,23.80,NA,NA,0.223118,29.470456,-788.163643,24.901313
31,24086.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,149600000,12912,27.60,18.84,NA,NA,0.420045,NA,NA,NA
32,24087.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,171200000,14246,25.20,18.64,NA,NA,0.159374,NA,NA,NA
33,24088.0,2024-05-30 00:30:00,2024-05-31 07:46:00,5.472,5.616,5.48,30.56,31.2,29.68,1,...,158400000,12912,26.88,13.24,NA,NA,0.402879,29.482326,5.9345,23.504175
34,24089.0,2024-05-30 00:30:00,2024-05-31 07:46:00,5.472,5.616,5.48,30.56,31.2,29.68,1,...,148000000,14246,27.68,15.00,NA,NA,0.425424,29.482326,5.9345,23.504175
35,24090.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,144800000,12912,26.08,19.56,NA,NA,0.100890,NA,NA,NA
36,24091.0,2024-06-02 00:30:00,2024-06-03 07:03:00,5.392,5.424,5.472,33.44,32.16,29.36,1,...,195200000,12912,30.48,27.76,NA,NA,0.561256,29.466291,6.003,23.420342
37,24092.0,2024-06-02 00:30:00,2024-06-03 07:03:00,5.392,5.424,5.472,33.44,32.16,29.36,1,...,223200000,17825,38.80,39.04,NA,NA,0.463361,29.466291,6.003,23.420342
38,24093.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,214400000,12912,23.76,22.12,NA,NA,0.130493,NA,NA,NA
39,24094.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,204800000,14246,22.32,19.72,NA,NA,0.136354,NA,NA,NA
40,24095.0,2024-06-09 00:30:00,2024-06-10 07:09:00,5.456,5.44,5.432,32.08,31.28,28.72,1,...,246400000,17825,42.32,35.28,NA,NA,0.455325,29.499504,5.897551,25.988391
41,24096.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,230400000,14246,33.92,31.40,NA,NA,0.008120,NA,NA,NA
42,24097.0,2024-06-09 00:30:00,2024-06-10 07:09:00,5.456,5.44,5.432,32.08,31.28,28.72,1,...,240800000,12912,37.12,18.84,NA,NA,0.413534,29.499504,5.897551,25.988391
43,24098.0,2024-06-13 00:30:00,2024-06-14 08:00:00,5.672,5.608,5.608,23.04,22.56,20.96,1,...,138400000,12912,32.00,14.48,NA,NA,0.431561,29.554252,5.952724,29.283132
44,24099.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,165600000,12912,29.60,18.60,NA,NA,0.100500,NA,NA,NA
45,24100.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,216800000,12912,32.80,24.64,NA,NA,0.119201,NA,NA,NA
46,24101.0,2024-06-27 00:30:00,2024-06-28 07:16:00,5.424,5.432,5.416,32.08,32.48,30.64,1,...,157600000,12912,31.84,23.48,NA,NA,0.432775,29.46313,5.9696,22.972185
47,24103.0,2024-06-27 00:30:00,2024-06-28 07:16:00,5.424,5.432,5.416,32.08,32.48,30.64,1,...,172800000,14246,29.44,19.76,NA,NA,0.438751,29.46313,5.9696,22.972185
48,24104.0,2024-06-30 00:30:00,2024-07-01 07:01:00,5.408,5.424,5.392,27.44,26.48,26.64,1,...,171200000,14246,30.80,20.56,NA,NA,0.553643,29.459663,5.96728,24.690989
49,24105.0,2024-06-30 00:30:00,2024-07-01 07:01:00,5.408,5.424,5.392,27.44,26.48,26.64,1,...,173600000,17825,31.84,19.16,NA,NA,0.353565,29.459663,5.96728,24.690989
50,24106.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,163200000,12912,32.40,26.40,NA,NA,0.119613,NA,NA,NA
51,24107.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,151200000,14246,28.32,23.28,NA,NA,0.118573,NA,NA,NA
52,24108.0,2024-07-04 00:30:00,2024-07-05 07:04:00,5.528,5.432,5.504,33.44,28.8,25.6,0,...,159200000,14246,29.92,15.40,NA,NA,0.425728,16.151028,800.287988,3.90363
53,24109.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,196000000,12912,31.84,28.68,NA,NA,0.104311,NA,NA,NA
54,24110.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,...,157600000,14246,34.40,27.80,NA,NA,0.944828,NA,NA,NA